"""empty message

Revision ID: 4edca851e8a1
Revises: d8b188fde541
Create Date: 2019-08-09 14:06:21.694066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edca851e8a1'
down_revision = 'd8b188fde541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('books_author_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['author_id'], ['id'])
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_author_fkey', 'books', 'users', ['author'], ['id'])
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
