"""empty message

Revision ID: d8b188fde541
Revises: 4b67f9146432
Create Date: 2019-08-09 14:00:13.855380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b188fde541'
down_revision = '4b67f9146432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author')
    # ### end Alembic commands ###
